/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence 
is generated by adding the previous two 
terms. By starting with 1 and 2, the 
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci 
sequence whose values do not exceed four 
million, find the sum of the even-valued terms.

SOLUTION: 4613732
*/

public class problem2 {


	public static float fib(int n) {
		// returns the nth fibonacci number
		if (n == 1) { 
			// base case
			return 1;
		}
		else {
			return fib(n-1) + fib(n-2);
		}
	}

	public static void main(String[] args) {
		// System.out.println(fib(1));
		// System.out.println(fib(2));
		// System.out.println(fib(3));
		// System.out.println(fib(4));
		// System.out.println(fib(5));
		int running_sum = 2;
		int previous = 2;
		int twice_previous = 1;
		int current = 3;
		while (current < 4000000) {
			if (current % 2 == 0) {
				// even term less than 4 mil
				running_sum += current;
			}
			twice_previous = previous;
			previous = current;
			current = previous + twice_previous;
		}
		System.out.println(running_sum);
	}
}